const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Touch,
		C3.Behaviors.Flash,
		C3.Plugins.Function,
		C3.Behaviors.Rotate,
		C3.Behaviors.NoSave,
		C3.Behaviors.Fade,
		C3.Behaviors.Bullet,
		C3.Plugins.Dictionary,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.TextBox,
		C3.Plugins.AJAX,
		C3.Behaviors.destroy,
		C3.Plugins.List,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Behaviors.Sin,
		C3.Behaviors.EightDir,
		C3.Plugins.Photon,
		C3.Behaviors.Tween,
		C3.Behaviors.MoveTo,
		C3.Plugins.PlatformInfo,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.Physics.Acts.SetIterations,
		C3.Behaviors.Physics.Acts.SetSteppingMode,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Physics.Acts.CreateDistanceJoint,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Physics.Acts.SetFriction,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Behaviors.Physics.Exps.AngularVelocity,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Physics.Exps.Mass,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Physics.Acts.ApplyTorque,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Physics.Acts.SetPreventRotate,
		C3.Behaviors.Physics.Acts.SetLinearDamping,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.AngleWithin,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Behaviors.Physics.Acts.RemoveJoints,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Behaviors.Physics.Acts.SetAngularDamping,
		C3.Behaviors.Physics.Acts.ApplyForce,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Plugins.TiledBg.Cnds.OnCreated,
		C3.Behaviors.Physics.Cnds.CompareAngularVelocity,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.List.Acts.SetVisible,
		C3.Plugins.List.Acts.SetEnabled,
		C3.Plugins.List.Acts.Select,
		C3.Plugins.List.Cnds.OnSelectionChanged,
		C3.Plugins.List.Acts.SetBlur,
		C3.Plugins.List.Cnds.CompareSelection,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetLayoutAngle,
		C3.Plugins.System.Exps.anglelerp,
		C3.Plugins.System.Exps.layoutangle,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.TiledBg.Exps.Count,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Behaviors.Physics.Acts.ApplyForceToward,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Sin.Acts.SetMovement,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.TiledBg.Acts.LoadURL,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.ScriptsInEvents.Menu_sheet_Event1_Act1,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.ScriptsInEvents.Menu_sheet_Event5_Act1,
		C3.ScriptsInEvents.Menu_sheet_Event6_Act1,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.SetRotateSpeed,
		C3.Behaviors.MoveTo.Exps.MaxSpeed,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.IID,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.System.Exps.layoutscale,
		C3.ScriptsInEvents.Garage_sheet_Event9_Act4,
		C3.ScriptsInEvents.Garage_sheet_Event10_Act1,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Cnds.EveryTick,
		C3.ScriptsInEvents.Ads_Event1_Act1,
		C3.ScriptsInEvents.Ads_Event1_Act2,
		C3.ScriptsInEvents.Ads_Event1_Act3,
		C3.ScriptsInEvents.Ads_Event1_Act4,
		C3.Plugins.System.Exps.timescale,
		C3.ScriptsInEvents.Ads_Event6_Act1,
		C3.ScriptsInEvents.Ads_Event7_Act1,
		C3.ScriptsInEvents.Carshop_sheet_Event6_Act4,
		C3.ScriptsInEvents.Carshop_sheet_Event7_Act1,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Photon.Acts.connect,
		C3.Plugins.Photon.Cnds.onError,
		C3.Plugins.Photon.Cnds.onJoinedLobby,
		C3.Plugins.Photon.Acts.joinRandomRoom,
		C3.Plugins.Photon.Cnds.onJoinRandomRoomNoMatchFound,
		C3.Plugins.Photon.Acts.createRoom,
		C3.Plugins.Photon.Acts.setMyRoomIsOpen,
		C3.Plugins.Photon.Acts.setMyRoomMaxPlayers,
		C3.Plugins.Photon.Cnds.onJoinRoom,
		C3.Plugins.Photon.Exps.MyActorNr,
		C3.Plugins.Photon.Acts.raiseEvent,
		C3.Plugins.Photon.Cnds.onEvent,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Photon.Exps.EventData,
		C3.Plugins.Photon.Cnds.onActorLeave,
		C3.Plugins.Photon.Exps.ActorNr,
		C3.Plugins.Photon.Exps.MasterActorNr,
		C3.Plugins.Photon.Exps.State,
		C3.Plugins.Photon.Exps.ActorCount,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Photon.Exps.StateString,
		C3.Plugins.Photon.Exps.RoomIsOpen,
		C3.Plugins.Photon.Exps.MyRoomName,
		C3.Plugins.Photon.Acts.leaveRoom,
		C3.Plugins.Photon.Acts.disconnect,
		C3.Plugins.Photon.Acts.setPropertyOfMyRoom,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Behaviors.Physics.Acts.CreateLimitedRevoluteJoint,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Photon.Exps.PropertyOfMyRoom,
		C3.Plugins.Function.Cnds.CompareParam,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Plugins.System.Acts.SetLayerScaleRate,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Cnds.CompareOpacity
	];
};
self.C3_JsPropNameTable = [
	{Gfill: 0},
	{deep: 0},
	{Physics: 0},
	{Ground: 0},
	{Groundtile: 0},
	{CaveBarder: 0},
	{Cave: 0},
	{break: 0},
	{bridge01: 0},
	{bridge2: 0},
	{bridge3: 0},
	{bridge4: 0},
	{bridge5: 0},
	{bridge6: 0},
	{bridge7: 0},
	{Bridgehold1: 0},
	{Bridgehold2: 0},
	{crack: 0},
	{Hanger: 0},
	{hangerhold1: 0},
	{hangerhold2: 0},
	{rope1: 0},
	{rope2: 0},
	{Keyboard: 0},
	{Anchor: 0},
	{Text: 0},
	{Touch: 0},
	{But_restart: 0},
	{trees: 0},
	{Speed: 0},
	{Handling: 0},
	{Acele_press: 0},
	{Jump: 0},
	{Flip: 0},
	{InWater: 0},
	{FlipInt: 0},
	{FlipOn: 0},
	{ID: 0},
	{UserName: 0},
	{Health: 0},
	{destory: 0},
	{Postion: 0},
	{Active: 0},
	{Px: 0},
	{Py: 0},
	{Pa: 0},
	{Flash: 0},
	{Player: 0},
	{Btire: 0},
	{BG: 0},
	{Ftire: 0},
	{coin: 0},
	{Function: 0},
	{Popup_text: 0},
	{Stars: 0},
	{FinishLine: 0},
	{info: 0},
	{Black: 0},
	{Rotate: 0},
	{Loader: 0},
	{But_start2: 0},
	{Status: 0},
	{But_next: 0},
	{Statuse: 0},
	{But_back: 0},
	{NoSave: 0},
	{But_setting: 0},
	{But_menu: 0},
	{But_car: 0},
	{But_ok: 0},
	{But_cancel: 0},
	{But_sound: 0},
	{Board: 0},
	{Fade: 0},
	{Bullet: 0},
	{Dirt: 0},
	{Shine: 0},
	{revers: 0},
	{aceletator: 0},
	{UI_text: 0},
	{Coin_show: 0},
	{star: 0},
	{locked: 0},
	{Lvl: 0},
	{Stars_store: 0},
	{Lvl_nth: 0},
	{Dictionary: 0},
	{Paint: 0},
	{Holder: 0},
	{Bar: 0},
	{Sys_Icon: 0},
	{Price: 0},
	{But_buy: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{min: 0},
	{sec: 0},
	{miniSec: 0},
	{Timer: 0},
	{Time_icon: 0},
	{Logo: 0},
	{Box: 0},
	{winlose: 0},
	{Browser: 0},
	{LevelInfo: 0},
	{Data: 0},
	{Title: 0},
	{colider: 0},
	{AJAX: 0},
	{Building: 0},
	{lamp: 0},
	{woodPice: 0},
	{wood: 0},
	{Woodbar: 0},
	{Container: 0},
	{grill: 0},
	{DestroyOutsideLayout: 0},
	{Explosion: 0},
	{Road: 0},
	{Roof: 0},
	{Lifebarback: 0},
	{Lifebar: 0},
	{VehicleSpawn: 0},
	{List: 0},
	{Move: 0},
	{stop: 0},
	{distance: 0},
	{Stone: 0},
	{current: 0},
	{highest: 0},
	{Info2: 0},
	{Flip_points: 0},
	{Bloodpr: 0},
	{CarPrice: 0},
	{adButton: 0},
	{reward_txt: 0},
	{lock: 0},
	{color: 0},
	{carSelec: 0},
	{Pin: 0},
	{sensor: 0},
	{headsen: 0},
	{But_Random: 0},
	{move: 0},
	{Sine: 0},
	{plant: 0},
	{bomb: 0},
	{Berriel: 0},
	{berrelRoller: 0},
	{Water: 0},
	{waterpar: 0},
	{bubbles: 0},
	{metalPis: 0},
	{Sprite: 0},
	{hit: 0},
	{"8Direction": 0},
	{freecamera: 0},
	{dark: 0},
	{loadiing: 0},
	{board2: 0},
	{Camra: 0},
	{LinGr: 0},
	{Solo: 0},
	{Multiplayer: 0},
	{Photon: 0},
	{Balck: 0},
	{Slot: 0},
	{CarLobbySpot: 0},
	{UserHi: 0},
	{ConnectInfo: 0},
	{InfoMulti: 0},
	{countDown: 0},
	{respawner: 0},
	{RaceFinishTx: 0},
	{dist: 0},
	{Myparcel: 0},
	{Parcel: 0},
	{Parcelclone: 0},
	{PlayerClone: 0},
	{cc: 0},
	{cc2: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{NearBG: 0},
	{TiledBackground2: 0},
	{MidBG: 0},
	{FarBG: 0},
	{SkyBG: 0},
	{Tween: 0},
	{MoreGameBtn: 0},
	{BrEgg: 0},
	{active: 0},
	{yogh: 0},
	{DistantVar: 0},
	{barpointer: 0},
	{HiscoreLine: 0},
	{EggStory: 0},
	{MoveTo: 0},
	{Asset115x: 0},
	{waypint: 0},
	{story: 0},
	{SkipBtn: 0},
	{storybtn: 0},
	{Finishlineicon: 0},
	{PlatformInfo: 0},
	{Guide4: 0},
	{Guideinfo: 0},
	{guideBg: 0},
	{But_buyAdd: 0},
	{Sys_Icon2: 0},
	{But_buySubc: 0},
	{Bar2: 0},
	{UI_Price: 0},
	{Vehicle_group: 0},
	{Button: 0},
	{HitDeath: 0},
	{Ground_obj: 0},
	{Ground_tiled: 0},
	{Bridge: 0},
	{graphics: 0},
	{BGfm: 0},
	{ZoomTr: 0},
	{Error_03: 0},
	{Overall_velocity: 0},
	{Cheat: 0},
	{Flips: 0},
	{Factor: 0},
	{Camera: 0},
	{health: 0},
	{Zoom: 0},
	{Sound: 0},
	{Coin_Store: 0},
	{Coin_current: 0},
	{Vehicle: 0},
	{VehicleColor: 0},
	{Wheel: 0},
	{Game_Status: 0},
	{WhoisShooted: 0},
	{Mode: 0},
	{Type: 0},
	{X: 0},
	{Y: 0},
	{DistanceCovered: 0},
	{adss: 0},
	{Cam: 0},
	{Current_Lvl: 0},
	{Current_stars: 0},
	{Progress: 0},
	{Story: 0},
	{Input: 0},
	{SpeedMax: 0},
	{JumpMax: 0},
	{Ads: 0},
	{GiveReward: 0},
	{adReward: 0},
	{canReward: 0},
	{adActive: 0},
	{MyActorID: 0},
	{ConnectingTime: 0},
	{TimeToContinue: 0},
	{Position: 0},
	{PlayersCount: 0},
	{SyncFactor: 0},
	{StoryNth: 0}
];

self.InstanceType = {
	Gfill: class extends self.ITiledBackgroundInstance {},
	Ground: class extends self.ISpriteInstance {},
	Groundtile: class extends self.ITiledBackgroundInstance {},
	CaveBarder: class extends self.ISpriteInstance {},
	Cave: class extends self.ITiledBackgroundInstance {},
	bridge01: class extends self.ISpriteInstance {},
	bridge2: class extends self.ISpriteInstance {},
	bridge3: class extends self.ISpriteInstance {},
	bridge4: class extends self.ISpriteInstance {},
	bridge5: class extends self.ISpriteInstance {},
	bridge6: class extends self.ISpriteInstance {},
	bridge7: class extends self.ISpriteInstance {},
	Bridgehold1: class extends self.ISpriteInstance {},
	Bridgehold2: class extends self.ISpriteInstance {},
	Hanger: class extends self.ISpriteInstance {},
	hangerhold1: class extends self.ISpriteInstance {},
	hangerhold2: class extends self.ISpriteInstance {},
	rope1: class extends self.ITiledBackgroundInstance {},
	rope2: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	But_restart: class extends self.ISpriteInstance {},
	trees: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Btire: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	Ftire: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	Popup_text: class extends self.ISpriteInstance {},
	Stars: class extends self.ISpriteInstance {},
	FinishLine: class extends self.ISpriteInstance {},
	info: class extends self.ITextInstance {},
	Black: class extends self.ITiledBackgroundInstance {},
	Loader: class extends self.ISpriteInstance {},
	But_start2: class extends self.ISpriteInstance {},
	But_next: class extends self.ISpriteInstance {},
	But_back: class extends self.ISpriteInstance {},
	But_setting: class extends self.ISpriteInstance {},
	But_menu: class extends self.ISpriteInstance {},
	But_car: class extends self.ISpriteInstance {},
	But_ok: class extends self.ISpriteInstance {},
	But_cancel: class extends self.ISpriteInstance {},
	But_sound: class extends self.ISpriteInstance {},
	Board: class extends self.ISpriteInstance {},
	Dirt: class extends self.ISpriteInstance {},
	Shine: class extends self.ISpriteInstance {},
	revers: class extends self.ISpriteInstance {},
	aceletator: class extends self.ISpriteInstance {},
	UI_text: class extends self.ITextInstance {},
	Coin_show: class extends self.ISpriteInstance {},
	Lvl: class extends self.ISpriteInstance {},
	Stars_store: class extends self.ISpriteInstance {},
	Lvl_nth: class extends self.ITextInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	Paint: class extends self.ISpriteInstance {},
	Holder: class extends self.ISpriteInstance {},
	Bar: class extends self.ISpriteInstance {},
	Sys_Icon: class extends self.ISpriteInstance {},
	But_buy: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Timer: class extends self.ISpriteInstance {},
	Time_icon: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	Box: class extends self.ISpriteInstance {},
	winlose: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	LevelInfo: class extends self.ITextInstance {},
	Data: class extends self.ITextInputInstance {},
	Title: class extends self.ISpriteInstance {},
	colider: class extends self.ITiledBackgroundInstance {},
	AJAX: class extends self.IInstance {},
	Building: class extends self.ISpriteInstance {},
	lamp: class extends self.ISpriteInstance {},
	woodPice: class extends self.ISpriteInstance {},
	wood: class extends self.ISpriteInstance {},
	Woodbar: class extends self.ITiledBackgroundInstance {},
	Container: class extends self.ISpriteInstance {},
	grill: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	Road: class extends self.ITiledBackgroundInstance {},
	Roof: class extends self.ITiledBackgroundInstance {},
	Jump: class extends self.ISpriteInstance {},
	Lifebarback: class extends self.ITiledBackgroundInstance {},
	Lifebar: class extends self.ITiledBackgroundInstance {},
	VehicleSpawn: class extends self.ISpriteInstance {},
	List: class extends self.IListInstance {},
	Stone: class extends self.ISpriteInstance {},
	Info2: class extends self.ITextInstance {},
	Flip_points: class extends self.ISpriteInstance {},
	Bloodpr: class extends self.IParticlesInstance {},
	CarPrice: class extends self.ITextInstance {},
	adButton: class extends self.ISpriteInstance {},
	reward_txt: class extends self.ITextInstance {},
	carSelec: class extends self.ISpriteInstance {},
	sensor: class extends self.ISpriteInstance {},
	headsen: class extends self.ISpriteInstance {},
	But_Random: class extends self.ISpriteInstance {},
	plant: class extends self.ISpriteInstance {},
	bomb: class extends self.ISpriteInstance {},
	Berriel: class extends self.ISpriteInstance {},
	berrelRoller: class extends self.ISpriteInstance {},
	Water: class extends self.ITiledBackgroundInstance {},
	waterpar: class extends self.IParticlesInstance {},
	bubbles: class extends self.IParticlesInstance {},
	metalPis: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	hit: class extends self.ISpriteInstance {},
	freecamera: class extends self.ISpriteInstance {},
	dark: class extends self.ITiledBackgroundInstance {},
	loadiing: class extends self.ITextInstance {},
	board2: class extends self.ISpriteInstance {},
	Camra: class extends self.ITiledBackgroundInstance {},
	LinGr: class extends self.ITiledBackgroundInstance {},
	Solo: class extends self.ISpriteInstance {},
	Multiplayer: class extends self.ISpriteInstance {},
	Photon: class extends self.IInstance {},
	Balck: class extends self.ITiledBackgroundInstance {},
	CarLobbySpot: class extends self.ISpriteInstance {},
	UserHi: class extends self.ITextInstance {},
	ConnectInfo: class extends self.ITextInstance {},
	InfoMulti: class extends self.ITextInstance {},
	countDown: class extends self.ISpriteInstance {},
	respawner: class extends self.ISpriteInstance {},
	RaceFinishTx: class extends self.ISpriteInstance {},
	Parcel: class extends self.ISpriteInstance {},
	Parcelclone: class extends self.ISpriteInstance {},
	PlayerClone: class extends self.ISpriteInstance {},
	cc: class extends self.ITextInstance {},
	cc2: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	NearBG: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	MidBG: class extends self.ITiledBackgroundInstance {},
	FarBG: class extends self.ITiledBackgroundInstance {},
	SkyBG: class extends self.ITiledBackgroundInstance {},
	MoreGameBtn: class extends self.ISpriteInstance {},
	BrEgg: class extends self.ISpriteInstance {},
	yogh: class extends self.ISpriteInstance {},
	DistantVar: class extends self.ISpriteInstance {},
	barpointer: class extends self.ISpriteInstance {},
	HiscoreLine: class extends self.ITiledBackgroundInstance {},
	EggStory: class extends self.ISpriteInstance {},
	Asset115x: class extends self.ISpriteInstance {},
	waypint: class extends self.ISpriteInstance {},
	story: class extends self.ISpriteInstance {},
	SkipBtn: class extends self.ISpriteInstance {},
	storybtn: class extends self.ISpriteInstance {},
	Finishlineicon: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	Guide4: class extends self.ISpriteInstance {},
	Guideinfo: class extends self.ITextInstance {},
	guideBg: class extends self.ITiledBackgroundInstance {},
	But_buyAdd: class extends self.ISpriteInstance {},
	Sys_Icon2: class extends self.ISpriteInstance {},
	But_buySubc: class extends self.ISpriteInstance {},
	Bar2: class extends self.ISpriteInstance {},
	UI_Price: class extends self.ITextInstance {},
	Vehicle_group: class extends self.ISpriteInstance {},
	Button: class extends self.ISpriteInstance {},
	HitDeath: class extends self.ISpriteInstance {},
	Ground_obj: class extends self.ISpriteInstance {},
	Ground_tiled: class extends self.ITiledBackgroundInstance {},
	Bridge: class extends self.ISpriteInstance {},
	graphics: class extends self.ISpriteInstance {},
	BGfm: class extends self.ITiledBackgroundInstance {}
}